public class notification {


    public static void test(string xRefID, string phoneNumber, string firstName, boolean isSMS, boolean isPush, string BrazeID){
        
       /* string xefID = xRefID;
        string phone = phoneNumber;
        string name = firstName;
        boolean issMss = isSMS;
        boolean ispushed = isPush;
        string brazeids = BrazeID;*/
        system.debug(xRefID);
        system.debug(phoneNumber);
        system.debug(firstName);
        system.debug(isSMS);
        system.debug(isPush);
        system.debug(BrazeID);
        

    }

}